// Pre-built work orders for 2018 Honda CR-V AWD 1.5T
// Current odometer: ~150,000 km

export const PRESET_WORK_ORDERS = [
  {
    id: 'wo-brakefld',
    title: 'Brake Fluid Replacement',
    priority: 'high',
    status: 'open',
    createdKm: 150000,
    createdAt: new Date().toISOString(),
    notes: 'Brake fluid is hygroscopic — it absorbs moisture over time, lowering its boiling point and increasing corrosion risk inside calipers and master cylinder. Was due at 130,000 km. DOT 3 minimum; DOT 4 acceptable and offers higher boiling point. Flush completely — do not top up.',
    procedure: [
      'Gather supplies: brake fluid (DOT 3 or DOT 4), clear tubing, catch bottle, turkey baster or fluid transfer pump, nitrile gloves.',
      'Park on level ground, engine off. Apply parking brake.',
      'Open hood. Locate brake fluid reservoir on driver side firewall. Check current fluid color — dark brown/black = contaminated.',
      'Use turkey baster or transfer pump to remove as much old fluid as possible from the reservoir. Do not let reservoir run completely dry.',
      'Fill reservoir to MAX line with fresh DOT 3 or DOT 4 fluid.',
      'Start at the furthest wheel from the master cylinder: Rear Passenger → Rear Driver → Front Passenger → Front Driver.',
      'For each wheel: remove wheel, locate bleeder screw on caliper (8mm or 10mm), attach clear tubing to bleeder screw, submerge other end in catch bottle with a bit of old fluid (prevents air suck-back).',
      'Have assistant slowly press brake pedal to floor and hold. Open bleeder screw 1/4 turn — old dark fluid will flow out. Close bleeder before assistant releases pedal. Repeat until fluid runs clear and bubble-free.',
      'After each wheel, check reservoir level and top up — never let it drop below MIN.',
      'Torque bleeder screws: 8–10 N·m. Do not overtighten — they strip easily.',
      'Reinstall wheels. Torque lug nuts: 108 N·m in star pattern.',
      'Pump brake pedal several times until firm. Test pedal feel before driving.',
      'Dispose of old fluid at recycling center — do not pour down drain.',
    ],
    parts: [
      { partNumber: '08798-9008', description: 'Honda DOT 3 Brake Fluid 500mL (OEM)', qty: 2, unit: 'bottle' },
      { partNumber: 'N/A', description: 'Clear vinyl tubing 30cm (bleeding tool)', qty: 1, unit: 'piece' },
    ],
  },
  {
    id: 'wo-diff',
    title: 'Rear Differential Fluid Replacement',
    priority: 'high',
    status: 'open',
    createdKm: 150000,
    createdAt: new Date().toISOString(),
    notes: 'The 2018 CR-V AWD uses a Real Time AWD system with an electronically controlled rear differential (VTM-4 type). Fluid is Honda DPS-F (Dual Pump System Fluid). Last done at 100,000 km — overdue at 150,000 km. Do not substitute with generic ATF — DPS-F is specific to this unit. Incorrect fluid will cause AWD shudder and premature wear.',
    procedure: [
      'Warm up vehicle with a 10-minute drive — warm fluid drains more completely.',
      'Lift vehicle on jack stands or drive onto ramps. Must be level for accurate fill.',
      'Locate rear differential under rear axle — aluminum housing between rear driveshafts.',
      'Locate FILL plug first (upper plug, 3/8" square drive) — confirm you can open it BEFORE opening drain plug. Never drain a diff you cannot refill.',
      'Remove fill plug. Inspect thread condition.',
      'Place drain pan under diff. Remove DRAIN plug (lower plug, 3/8" square drive). Allow full drain — approximately 5–10 minutes.',
      'Inspect drain plug magnet for metal particles. Fine gray sludge is normal. Metallic chunks indicate bearing wear — inspect further.',
      'Clean drain plug threads. Install new drain plug washer if reusing plug.',
      'Reinstall drain plug. Torque: 40 N·m.',
      'Using fluid pump through fill hole, add Honda DPS-F fluid until it begins to seep out of fill hole (this is the correct level).',
      'Reinstall fill plug. Torque: 40 N·m.',
      'Wipe clean. Lower vehicle.',
      'Test drive — include turns at low speed to verify no AWD shudder.',
    ],
    parts: [
      { partNumber: '08200-9007', description: 'Honda DPS-F Dual Pump Fluid 1L', qty: 1, unit: 'bottle' },
      { partNumber: '90471-PX4-000', description: 'Drain/Fill Plug Sealing Washer (x2 needed)', qty: 2, unit: 'each' },
    ],
  },
  {
    id: 'wo-airfilter',
    title: 'Engine Air Filter Replacement',
    priority: 'high',
    status: 'open',
    createdKm: 150000,
    createdAt: new Date().toISOString(),
    notes: 'Air filter was last replaced at 120,000 km — now 30,000 km overdue. A clogged air filter increases fuel consumption, can contribute to oil dilution on the 1.5T turbo (restricted airflow = richer mixture), and reduces power. In White River conditions (gravel roads, dust, insects), inspect every 15,000 km even if not replacing.',
    procedure: [
      'Open hood. Air filter box is located on driver side, connected to the turbo inlet pipe.',
      'Loosen the large intake hose clamp connecting the airbox outlet to the turbo inlet pipe (8mm or 10mm hex).',
      'Unclip the 4 plastic clips holding the airbox lid. Lift lid.',
      'Remove old air filter. Note orientation before removal.',
      'Inspect airbox interior — remove any debris, insects, leaves.',
      'Install new filter — confirm rubber seal seats fully around perimeter.',
      'Reinstall airbox lid, engage all 4 clips.',
      'Reconnect intake hose, tighten clamp snugly — do not overtighten (plastic inlet can crack).',
      'Start engine, check for any intake noise or boost leaks.',
    ],
    parts: [
      { partNumber: '17220-5PA-A00', description: 'OEM Honda Engine Air Filter — 1.5T (2017–2022 CR-V)', qty: 1, unit: 'each' },
    ],
  },
  {
    id: 'wo-cabinair',
    title: 'Cabin Air Filter Replacement',
    priority: 'medium',
    status: 'open',
    createdKm: 150000,
    createdAt: new Date().toISOString(),
    notes: 'Cabin air filter was last replaced at 145,000 km — approaching next service at 160,000 km. In White River, pollen, road dust, and insects can clog this filter faster than normal. A restricted cabin filter reduces HVAC airflow, causes blower motor to work harder, and allows unfiltered air to enter cabin.',
    procedure: [
      'Open glove box.',
      'Empty glove box contents.',
      'Squeeze both sides of glove box inward (compress the side tabs) to allow it to swing fully down past the stop tabs.',
      'The cabin air filter housing is now visible — a rectangular cover with a tab or clip.',
      'Slide out the old filter. Note airflow direction arrow on the filter frame.',
      'Check housing interior for debris — wipe out with dry cloth if needed.',
      'Insert new filter with arrow pointing DOWN (airflow direction toward blower).',
      'Close filter housing cover.',
      'Swing glove box back up, squeeze sides to re-engage stop tabs.',
      'Test HVAC — verify airflow is improved.',
    ],
    parts: [
      { partNumber: '80292-TBA-A11', description: 'OEM Honda Cabin Air Filter — 2017–2022 CR-V', qty: 1, unit: 'each' },
    ],
  },
  {
    id: 'wo-tires',
    title: 'Tire Rotation',
    priority: 'medium',
    status: 'open',
    createdKm: 150000,
    createdAt: new Date().toISOString(),
    notes: 'Tire rotation equalizes wear across all four tires. On the AWD CR-V, front tires typically wear faster due to steering load. Next rotation due at 160,000 km. Use a modified X-pattern (non-directional tires) or straight front-to-rear swap (directional tires). Tires: 235/60R18. Check for directional arrow on sidewall before rotating.',
    procedure: [
      'Confirm tire type: check sidewall for directional arrow. Directional = front/rear swap only (same side). Non-directional = full X-pattern.',
      'Loosen all lug nuts slightly while tires are on ground (118 ft·lb = 160 N·m).',
      'Lift vehicle. Use proper jack points — refer to owner manual. Use jack stands.',
      'Remove all 4 wheels.',
      'Inspect each tire: tread depth (minimum 3mm), sidewall cracks, bulges, uneven wear patterns. Record findings.',
      'Inspect brake components while wheels are off: rotor condition, pad thickness, caliper slides.',
      'For non-directional tires (X-pattern): Front Right → Rear Left. Front Left → Rear Right. Rear Right → Front Left. Rear Left → Front Right.',
      'For directional tires: Front Right → Rear Right. Front Left → Rear Left.',
      'Reinstall wheels. Hand-tighten lug nuts.',
      'Lower vehicle to ground.',
      'Torque lug nuts to 108 N·m (80 ft·lb) in star pattern. Two passes recommended.',
      'Check and adjust tire pressure: 33 PSI front, 33 PSI rear (cold). Adjust for load if needed.',
      'Test drive. Listen for vibration or pulling — if present, re-check torque and balance.',
    ],
    parts: [
      { partNumber: 'N/A', description: 'No parts required — service only', qty: 1, unit: 'each' },
    ],
  },
  {
    id: 'wo-oil',
    title: 'Engine Oil & Filter Change',
    priority: 'medium',
    status: 'open',
    createdKm: 150000,
    createdAt: new Date().toISOString(),
    notes: '2018 CR-V 1.5T is known for oil dilution in cold climates — gasoline from short trips in cold weather (White River winters) can contaminate the oil, reducing viscosity and lubrication. Use only 0W-20 full synthetic. Change every 8,000 km maximum — consider 6,000 km intervals during winter months. Check oil level and smell monthly during winter: if oil smells like gasoline or level is above MAX, change immediately regardless of km.',
    procedure: [
      'Warm engine for 5 minutes — warm oil drains faster and carries more contaminants.',
      'Gather: oil filter, 5.5L of 0W-20 full synthetic (4.4L capacity + extra), drain pan, 17mm socket, oil filter wrench, funnel, shop rags.',
      'Lift vehicle or use ramps. Locate oil drain plug on bottom of oil pan — 17mm bolt.',
      'Remove oil filler cap on top of engine (keeps suction from slowing drain).',
      'Place drain pan. Remove drain plug — turn counterclockwise. Allow full drain (5+ minutes).',
      'Move drain pan under oil filter. Oil filter is on passenger side of engine block. Remove with filter wrench — counterclockwise.',
      'Before installing new filter: apply thin film of fresh oil to new filter gasket.',
      'Install new filter hand-tight + 3/4 turn. Do not use wrench to install.',
      'Inspect drain plug washer — replace if crushed or damaged.',
      'Reinstall drain plug. Torque: 30 N·m. Do not overtighten.',
      'Lower vehicle.',
      'Add 4.4L of 0W-20 through filler cap. Install cap.',
      'Start engine. Oil pressure light should go out within 3 seconds. Check under vehicle for leaks.',
      'Shut off engine. Wait 3 minutes. Check dipstick — should read between MIN and MAX.',
      'Reset oil life indicator: hold TRIP button on instrument cluster while ignition is on, or use infotainment menu depending on trim.',
      'Record date, km, and oil brand used.',
    ],
    parts: [
      { partNumber: '15400-PLM-A02', description: 'OEM Honda Oil Filter — 1.5T Engine', qty: 1, unit: 'each' },
      { partNumber: '90471-PX4-000', description: 'Drain Plug Sealing Washer', qty: 1, unit: 'each' },
      { partNumber: 'N/A', description: '0W-20 Full Synthetic Engine Oil (e.g. Honda Genuine, Mobil 1, Castrol Edge)', qty: 5, unit: 'L' },
    ],
  },
]
