// Pre-built work orders — 2018 Honda CR-V AWD 1.5T
// Updated from Erick's maintenance schedule — White River, Ontario

export const PRESET_WORK_ORDERS = [

  // ── OVERDUE ──────────────────────────────────────────────
  {
    id: 'wo-brakefld',
    title: 'Brake Fluid Replacement',
    priority: 'high',
    status: 'open',
    createdKm: 150000,
    createdAt: new Date().toISOString(),
    notes: 'OVERDUE since 130,000 km. Brake fluid is hygroscopic — absorbs moisture over time, lowering boiling point and corroding calipers and master cylinder. DOT 3 minimum; DOT 4 acceptable and offers higher boiling point. Flush completely — never top up contaminated fluid.',
    procedure: [
      'Gather: DOT 3 or DOT 4 brake fluid (2 bottles), clear vinyl tubing ~30cm, catch bottle, turkey baster or fluid transfer pump, 8mm or 10mm wrench, nitrile gloves, shop rags.',
      'Park on level ground, engine off, parking brake applied.',
      'Open hood. Locate brake fluid reservoir on driver-side firewall. Check fluid color — dark brown or black means heavily contaminated.',
      'Use turkey baster to remove as much old fluid as possible from reservoir. Do NOT let reservoir run completely dry.',
      'Fill reservoir to MAX line with fresh fluid.',
      'Bleed order (furthest from master cylinder first): Rear Passenger → Rear Driver → Front Passenger → Front Driver.',
      'For each wheel: lift vehicle, locate bleeder screw on caliper, attach clear tubing to bleeder nipple, submerge other end in catch bottle with a bit of old fluid to prevent air suck-back.',
      'Have assistant slowly press brake pedal to floor and hold. Open bleeder 1/4 turn — dark fluid flows out. Close bleeder BEFORE assistant releases pedal. Repeat until fluid runs clear and bubble-free (typically 4–6 pumps per wheel).',
      'After each wheel, check reservoir and top up — never let it drop below MIN.',
      'Torque bleeder screws: 8–10 N·m. Do not overtighten — they strip easily.',
      'Reinstall wheels. Torque lug nuts: 108 N·m in star pattern.',
      'Pump brake pedal several times until firm. Check for leaks under vehicle.',
      'Test pedal feel — should be firm before moving vehicle.',
      'Dispose of old fluid at recycling center — do not pour down drain.',
    ],
    parts: [
      { partNumber: '08798-9008', description: 'Honda DOT 3 Brake Fluid 500mL', qty: 2, unit: 'bottle' },
      { partNumber: 'N/A', description: 'Clear vinyl tubing ~30cm (bleeding tool)', qty: 1, unit: 'piece' },
    ],
  },

  {
    id: 'wo-diff',
    title: 'Rear Differential Fluid Replacement',
    priority: 'high',
    status: 'open',
    createdKm: 150000,
    createdAt: new Date().toISOString(),
    notes: 'OVERDUE — last done at 100,000 km, due at 150,000 km. The AWD system uses Honda DPS-F (Dual Pump System Fluid) — do NOT substitute with generic ATF or any other fluid. Wrong fluid causes AWD shudder, clutch pack wear, and premature failure. Fill to overflow — do not guess the quantity.',
    procedure: [
      'Warm up vehicle with a 10-minute drive — warm fluid drains more completely.',
      'Lift vehicle on jack stands or ramps. Must be level for accurate fill.',
      'Locate rear differential — aluminum housing under rear axle between rear driveshafts.',
      'CRITICAL: Locate FILL plug first (upper plug, 3/8" square drive). Confirm you can open it BEFORE opening drain plug. Never drain a diff you cannot refill.',
      'Remove fill plug. Inspect thread condition.',
      'Place drain pan under diff. Remove DRAIN plug (lower plug, 3/8" square drive). Allow full drain — 5–10 minutes.',
      'Inspect drain plug magnet for metal particles. Fine gray sludge is normal. Large metallic chunks indicate bearing wear — investigate further.',
      'Clean drain plug threads. Install new sealing washer.',
      'Reinstall drain plug. Torque: 40 N·m.',
      'Using fluid pump through fill hole, add Honda DPS-F until fluid seeps out of fill hole — this is the correct level.',
      'Reinstall fill plug with new sealing washer. Torque: 40 N·m.',
      'Wipe clean. Lower vehicle.',
      'Test drive — include low-speed turns to verify no AWD shudder or binding.',
    ],
    parts: [
      { partNumber: '08200-9007', description: 'Honda DPS-F Dual Pump Fluid 1L', qty: 1, unit: 'bottle' },
      { partNumber: '90471-PX4-000', description: 'Drain/Fill Plug Sealing Washer (need 2)', qty: 2, unit: 'each' },
    ],
  },

  {
    id: 'wo-carbon',
    title: 'Intake Valve Carbon Deposit Cleaning',
    priority: 'high',
    status: 'open',
    createdKm: 150000,
    createdAt: new Date().toISOString(),
    notes: 'OVERDUE. The 1.5T is a GDI (Gasoline Direct Injection) engine — fuel is injected directly into the cylinder and never touches the intake valves, so carbon deposits accumulate on the back of the valves over time. Buildup causes rough idle, misfires, reduced power, and poor fuel economy. Walnut shell blasting is the proper method. This is a shop job unless you have the specialized blasting equipment.',
    procedure: [
      'NOTE: This service requires walnut shell blasting equipment. If you do not have this tool, take to a trusted shop. Estimated cost $200–$400. Describe the service as "GDI intake valve walnut blast cleaning."',
      'If doing DIY with blasting kit: disconnect intake hose from throttle body.',
      'Remove intake manifold to access intake ports (8mm bolts, note vacuum line locations before removal).',
      'Rotate engine so cylinder 1 intake valves are closed (both valves seated). Use blasting wand in intake port.',
      'Blast walnut shells at closed valves — shell fragments break off carbon deposits without damaging valve seats.',
      'Vacuum out all walnut shell debris from port before moving to next cylinder.',
      'Repeat for all 4 cylinders, rotating engine to close each cylinder\'s intake valves before blasting.',
      'Inspect ports with flashlight — valves should appear clean and shiny.',
      'Reinstall intake manifold with new gasket if old gasket shows any damage.',
      'Reconnect all vacuum lines and intake hose.',
      'Start engine — expect rough idle for 1–2 minutes as remaining debris clears.',
      'Check for intake manifold vacuum leaks with smoke test or carb cleaner (carefully).',
      'Note: Use top-tier fuel going forward (Petro-Canada, Shell V-Power) and consider catch can installation to reduce future buildup.',
    ],
    parts: [
      { partNumber: 'N/A', description: 'Intake manifold gasket set (replace if disturbed)', qty: 1, unit: 'set' },
      { partNumber: 'N/A', description: 'Walnut shell blast media (if DIY)', qty: 1, unit: 'bag' },
    ],
  },

  {
    id: 'wo-swaybar',
    title: 'Sway Bar End Links Inspection & Replacement',
    priority: 'high',
    status: 'open',
    createdKm: 150000,
    createdAt: new Date().toISOString(),
    notes: 'OVERDUE by mileage. Sway bar end links connect the sway bar to the strut assembly. Worn end links cause clunking over bumps, especially on White River gravel roads. Typical failure at 150,000–200,000 km in harsh climates. Inspect first — replace if worn, loose, or if rubber boot is cracked.',
    procedure: [
      'Lift vehicle on jack stands. Safely support vehicle — do not work under vehicle on jack only.',
      'Locate front sway bar end links — one per side, connecting sway bar to bottom of strut.',
      'Inspect rubber boots on each end link ball joint — cracking or torn boots mean the joint is contaminated and worn.',
      'Grab each end link and check for play — any looseness means replacement is needed.',
      'Check for clunking by pushing/pulling on sway bar while someone rocks the vehicle.',
      'To replace: hold center of end link with 6mm hex key to prevent spinning, remove upper nut (14mm) and lower nut (14mm).',
      'Remove old end link.',
      'Install new end link — hand tighten both ends first.',
      'Torque end link nuts: 38–44 N·m. Hold center stud with hex key to prevent spinning.',
      'Repeat on other side.',
      'Lower vehicle. Test drive on rough surface — clunking should be eliminated.',
    ],
    parts: [
      { partNumber: '51320-TLA-A01', description: 'Front Sway Bar End Link Left', qty: 1, unit: 'each' },
      { partNumber: '51320-TLA-A11', description: 'Front Sway Bar End Link Right', qty: 1, unit: 'each' },
    ],
  },

  // ── DUE SOON ─────────────────────────────────────────────
  {
    id: 'wo-oil',
    title: 'Engine Oil & Filter Change — Liquimoly 0W-20',
    priority: 'medium',
    status: 'open',
    createdKm: 150000,
    createdAt: new Date().toISOString(),
    notes: 'Next due at 164,000 km (5,000 km interval — White River winter protocol). The 1.5T is known for oil dilution in cold climates — gasoline seeps into oil during short cold-weather trips, thinning the lubricant. Use Liquimoly 0W-20 full synthetic as specified. During winter months, check oil level AND smell monthly. If oil smells like gasoline or is above MAX on dipstick, change immediately regardless of km.',
    procedure: [
      'Gather: Liquimoly 0W-20 full synthetic 5L, oil filter 15400-PLM-A02, drain plug washer 90471-PX4-000, drain pan, 17mm socket, oil filter wrench, funnel, gloves.',
      'Warm engine 5 minutes — warm oil drains faster and carries more contaminants out.',
      'Lift vehicle on ramps or jack stands.',
      'Remove oil filler cap on top of engine — this prevents vacuum slowing the drain.',
      'Place drain pan under oil pan. Remove drain plug (17mm) — counterclockwise. Allow full drain (5+ minutes).',
      'Move drain pan under oil filter on passenger side of engine block. Remove filter with wrench — counterclockwise. Expect oil spillage.',
      'Before installing new filter: apply thin film of fresh oil to new filter rubber gasket.',
      'Install new filter hand-tight + 3/4 additional turn. Do NOT use wrench to tighten.',
      'Install new drain plug washer. Reinstall drain plug. Torque: 30 N·m. Do not overtighten.',
      'Lower vehicle.',
      'Add 4.4L of Liquimoly 0W-20 through filler cap. Install cap.',
      'Start engine. Oil pressure warning light should extinguish within 3 seconds. If it stays on after 5 seconds — shut off immediately.',
      'Check under vehicle for leaks at drain plug and filter.',
      'Shut off engine. Wait 3 minutes. Check dipstick — should read between MIN and MAX lines.',
      'Reset oil life indicator: hold TRIP button on instrument cluster with ignition on until oil life resets, or through infotainment Settings menu.',
      'Record date, odometer, and oil brand in Oil Change Log tab of your Excel file.',
    ],
    parts: [
      { partNumber: '15400-PLM-A02', description: 'OEM Honda Oil Filter — 1.5T Engine', qty: 1, unit: 'each' },
      { partNumber: '90471-PX4-000', description: 'Drain Plug Sealing Washer', qty: 1, unit: 'each' },
      { partNumber: 'N/A', description: 'Liquimoly 0W-20 Full Synthetic', qty: 5, unit: 'L' },
    ],
  },

  {
    id: 'wo-tires',
    title: 'Tire Rotation',
    priority: 'medium',
    status: 'open',
    createdKm: 150000,
    createdAt: new Date().toISOString(),
    notes: 'Due at 160,000 km. CRITICAL on AWD — the Real Time AWD rear coupling is sensitive to tire circumference differences between axles. Uneven tread wear overworks the rear coupling and causes premature failure. Check sidewall for directional arrow before rotating — directional tires cannot be crossed side to side.',
    procedure: [
      'Check sidewall of each tire for directional arrow. If present: front-to-rear only (same side). If no arrow: full X-pattern rotation.',
      'Loosen all lug nuts slightly while tires are on ground. Torque: 108 N·m (80 ft·lb).',
      'Lift vehicle. Use proper jack points per owner manual. Support on jack stands.',
      'Remove all 4 wheels.',
      'Inspect each tire: tread depth (min 3mm, 4mm for winter), sidewall cracking, bulges, uneven wear patterns. Record findings.',
      'Inspect brake components while wheels are off: rotor thickness and scoring, pad thickness, caliper slide condition.',
      'Inspect CV axle boots for cracking or grease fling.',
      'Check sway bar end links and ball joints for play.',
      'NON-DIRECTIONAL rotation (X-pattern): Front Right → Rear Left. Front Left → Rear Right. Rear Right → Front Left. Rear Left → Front Right.',
      'DIRECTIONAL rotation: Front Right → Rear Right. Front Left → Rear Left.',
      'Reinstall wheels. Hand-tighten lug nuts in star pattern.',
      'Lower vehicle to ground.',
      'Torque lug nuts to 108 N·m in star pattern. Two full passes recommended.',
      'Check and adjust tire pressure — 33 PSI cold all around for 235/60R18.',
      'Test drive. Listen for vibration or pulling. If present, re-check torque and consider balance.',
    ],
    parts: [
      { partNumber: 'N/A', description: 'No parts required — service only', qty: 1, unit: 'each' },
    ],
  },

  {
    id: 'wo-cabinair',
    title: 'Cabin Air Filter Replacement',
    priority: 'medium',
    status: 'open',
    createdKm: 150000,
    createdAt: new Date().toISOString(),
    notes: 'Due at 170,000 km (20,000 km interval). A clogged cabin filter reduces HVAC airflow, makes the blower motor work harder, and allows unfiltered air into the cabin. In White River conditions — insects, dust, pollen, road debris — inspect every 15,000 km even if not replacing.',
    procedure: [
      'Open glove box and empty it completely.',
      'Squeeze both sides of the glove box inward — compressing the side tabs — to allow it to swing fully down past the stop tabs.',
      'The cabin air filter housing is now visible — a rectangular cover with a tab or clip on the right side.',
      'Release the clip and slide out the old filter. Note the airflow direction arrow printed on the filter frame.',
      'Inspect housing interior for debris, insects, leaves — wipe out with dry cloth if needed.',
      'Insert new filter with arrow pointing DOWN (airflow direction is toward blower motor).',
      'Close filter housing cover and engage clip.',
      'Swing glove box back up — squeeze sides to re-engage stop tabs. Reload contents.',
      'Turn on HVAC fan to full speed and verify improved airflow.',
    ],
    parts: [
      { partNumber: '80292-TBA-A11', description: 'OEM Honda Cabin Air Filter — 2017–2022 CR-V', qty: 1, unit: 'each' },
    ],
  },

  {
    id: 'wo-coolant',
    title: 'Engine Coolant Flush & Replacement',
    priority: 'medium',
    status: 'open',
    createdKm: 150000,
    createdAt: new Date().toISOString(),
    notes: 'Due at 170,000 km (last done 120,000 km). Use Honda Type 2 (blue) coolant ONLY. Do NOT mix with green, orange, or universal coolant — chemical incompatibility causes corrosion and gel buildup. The 1.5T aluminum engine block is particularly susceptible to coolant-related corrosion. Flush completely — do not just top up.',
    procedure: [
      'Allow engine to cool completely — minimum 2 hours after last operation. Never open radiator cap on hot engine.',
      'Gather: Honda Type 2 coolant (OL999-9011) 2 bottles, distilled water, drain pan, funnel, coolant tester.',
      'Place drain pan under radiator. Locate radiator drain petcock on bottom of radiator — turn counterclockwise to open.',
      'Open coolant reservoir cap on top of engine to allow faster draining.',
      'Allow complete drain — 10+ minutes. Close petcock.',
      'Fill system with distilled water only. Start engine, run to operating temp (5 minutes), then drain again. This flush removes remaining old coolant.',
      'Close petcock. Fill system with 50/50 mix of Honda Type 2 coolant and distilled water.',
      'Capacity: approximately 5.1L total for 2018 CR-V 1.5T.',
      'Fill radiator to base of neck. Fill reservoir to MAX line.',
      'Leave reservoir cap off. Start engine and let idle. Watch for air bubbles in reservoir — this is normal as system purges air.',
      'With heater on MAX, run engine until thermostat opens (temp gauge reaches middle). Top up coolant as level drops from air purging.',
      'Once temp stabilizes and no more bubbles, install reservoir cap.',
      'Check for leaks at petcock, hose clamps, and reservoir cap.',
      'After 1 drive cycle, recheck coolant level when cold — top up if needed.',
      'Test coolant freeze protection with tester — should read good to at least -40°C for White River conditions.',
    ],
    parts: [
      { partNumber: 'OL999-9011', description: 'Honda Type 2 Blue Coolant 1L', qty: 4, unit: 'bottle' },
      { partNumber: 'N/A', description: 'Distilled water (use only — not tap water)', qty: 2, unit: 'L' },
    ],
  },

  {
    id: 'wo-caliper',
    title: 'Brake Caliper Slides & Hardware Service',
    priority: 'medium',
    status: 'open',
    createdKm: 150000,
    createdAt: new Date().toISOString(),
    notes: 'Due at 170,000 km. White River salt and road grit seize caliper slides, causing uneven pad wear, brake pull, and heat buildup. This is a quick service — do at every pad inspection. Seized slides are one of the most common brake problems in Northern Ontario.',
    procedure: [
      'Lift vehicle and remove wheels. Start with one axle at a time.',
      'Visually inspect brake pads — measure thickness. Replace if under 3mm.',
      'Locate caliper slide pins — two per caliper (upper and lower), covered by rubber boots.',
      'Remove caliper bolts (12mm or 14mm). Hang caliper from spring or wire — do not let it hang by brake hose.',
      'Slide out caliper slide pins. Inspect rubber boots for cracking — replace if torn.',
      'Clean slide pin bores with wire brush or clean rag. Remove all old grease and corrosion.',
      'Inspect slide pins — should be smooth with no pitting. Replace if corroded.',
      'Apply fresh caliper slide grease (silicone-based, not petroleum) to slide pins. Coat entire pin surface.',
      'Reinstall slide pins. Verify boots are properly seated.',
      'Check caliper piston movement — depress piston with C-clamp or caliper tool. Should move smoothly.',
      'Check brake pad anti-squeal shims — clean contact points and apply brake quiet gel.',
      'Reinstall caliper. Torque caliper bolts: 27–33 N·m.',
      'Reinstall wheel. Torque lug nuts: 108 N·m.',
      'Pump brake pedal several times until firm before moving vehicle.',
      'Test drive — verify no brake pull or dragging.',
    ],
    parts: [
      { partNumber: 'N/A', description: 'Caliper slide pin grease (silicone-based)', qty: 1, unit: 'tube' },
      { partNumber: 'N/A', description: 'Brake caliper hardware kit (if slides worn)', qty: 1, unit: 'kit' },
    ],
  },

  // ── OK / SCHEDULED ────────────────────────────────────────
  {
    id: 'wo-airfilter',
    title: 'Engine Air Filter Replacement',
    priority: 'low',
    status: 'open',
    createdKm: 150000,
    createdAt: new Date().toISOString(),
    notes: 'Due at 170,000 km (10,000 km interval — shortened from 30K due to White River gravel roads). A clogged air filter increases fuel consumption, can worsen oil dilution on the 1.5T (restricted airflow = richer mixture), and reduces turbo efficiency. On gravel roads, inspect every service.',
    procedure: [
      'Open hood. Air filter box is on driver side, connected to the turbo inlet pipe.',
      'Loosen the large hose clamp connecting the airbox outlet to the turbo inlet pipe (8mm or 10mm).',
      'Unclip the 4 plastic clips holding the airbox lid. Two on front, two on back.',
      'Lift airbox lid. Remove old air filter.',
      'Inspect airbox interior — remove any debris, insects, leaves, or moisture.',
      'Hold old filter up to light — if light barely passes through, it was definitely due.',
      'Install new filter — confirm the rubber seal seats fully around the entire perimeter of the airbox.',
      'Reinstall airbox lid, engage all 4 clips. Verify all clips are fully snapped.',
      'Reconnect intake hose, tighten clamp snugly — do not overtighten (plastic inlet can crack).',
      'Start engine. Listen for any intake noise, hissing, or boost leaks.',
    ],
    parts: [
      { partNumber: '17220-5PA-A00', description: 'OEM Honda Engine Air Filter — 1.5T 2017–2022 CR-V', qty: 1, unit: 'each' },
    ],
  },

  {
    id: 'wo-cvt',
    title: 'CVT Fluid Pan-Drop Service',
    priority: 'medium',
    status: 'open',
    createdKm: 150000,
    createdAt: new Date().toISOString(),
    notes: 'Due at 200,000 km (50,000 km interval from last service at 150,000 km). Honda HCF-2 ONLY — using any other fluid will destroy the CVT. The pan-drop method replaces approximately 4.5 qt (partial change). This is not a full flush — a full CVT flush requires specialized equipment. The pan-drop is the correct DIY method.',
    procedure: [
      'Gather: Honda HCF-2 fluid (5 qt minimum), new CVT pan filter 25420-5LJ-003, pan gasket 21814-RJ2-003, top filter 25450-P4V-013, drain pan, 3/8" drive ratchet, torque wrench.',
      'Warm up transmission with 10-minute drive — warm fluid drains more completely.',
      'Lift vehicle on jack stands. Locate CVT pan under vehicle — aluminum pan with multiple bolts.',
      'Place large drain pan under CVT pan. Remove all pan bolts (10mm) starting from corners.',
      'Lower pan carefully — fluid will spill as last bolts are removed. Allow full drain.',
      'Remove old pan filter — it pulls straight down. Note orientation.',
      'Inspect pan for metal debris — fine particles are normal. Chunks or flakes indicate internal wear.',
      'Clean pan interior thoroughly with clean lint-free cloth. Clean mating surface on transmission case.',
      'Install new top filter 25450-P4V-013 if accessible (requires dropping valve body on some models — skip if not accessible).',
      'Install new pan filter 25420-5LJ-003 — push straight up until it clicks into place.',
      'Install new pan gasket 21814-RJ2-003 on pan — do not use RTV sealant.',
      'Reinstall pan. Torque bolts in crisscross pattern: 12 N·m (do NOT overtighten — aluminum threads strip easily).',
      'Refill with Honda HCF-2: approximately 4.5 qt (4.3L) through dipstick tube or fill port.',
      'Start engine, shift through all gear positions (P-R-N-D-L), return to P. Let idle 2 minutes.',
      'Check fluid level with engine running and transmission at operating temp. Add fluid to reach correct level on dipstick.',
      'Check for leaks at pan. Test drive — verify smooth CVT operation and no slipping.',
    ],
    parts: [
      { partNumber: '25420-5LJ-003', description: 'CVT Pan Filter', qty: 1, unit: 'each' },
      { partNumber: '21814-RJ2-003', description: 'CVT Pan Gasket', qty: 1, unit: 'each' },
      { partNumber: '25450-P4V-013', description: 'CVT Top Filter', qty: 1, unit: 'each' },
      { partNumber: 'N/A', description: 'Honda HCF-2 CVT Fluid', qty: 5, unit: 'qt' },
    ],
  },

  {
    id: 'wo-sparkplug',
    title: 'Spark Plugs Replacement & Valve Adjustment',
    priority: 'medium',
    status: 'open',
    createdKm: 150000,
    createdAt: new Date().toISOString(),
    notes: 'Due at 200,000 km. NGK Laser Iridium plugs — do NOT re-gap iridium tips, they are factory pre-set at 0.030 in (0.75mm). Re-gapping damages the iridium coating. Valve adjustment requires checking clearance on cold engine — spec: intake 0.18–0.22mm, exhaust 0.23–0.27mm. If clearances are within spec, no adjustment needed.',
    procedure: [
      'Allow engine to cool completely — valve adjustment requires cold engine. Minimum 3 hours after last operation.',
      'Gather: 4x NGK Iridium plugs 12290-59B-A01, spark plug socket (5/8"), torque wrench, feeler gauges (0.18–0.27mm range), valve cover gasket set.',
      'Remove engine cover (plastic, 4 bolts or clips).',
      'Disconnect ignition coil connectors — press tab and pull straight back.',
      'Remove ignition coil bolts (10mm) and pull coils straight up.',
      'Remove spark plugs with 5/8" spark plug socket. Inspect old plugs — wear pattern indicates engine health.',
      'Install new plugs hand tight, then torque to 18 N·m (13 ft·lb). Do NOT overtighten — aluminum head threads strip.',
      'Reinstall coils. Torque coil bolts: 9 N·m. Reconnect connectors.',
      'VALVE ADJUSTMENT: Remove valve cover bolts in crisscross pattern. Lift valve cover.',
      'Rotate engine to TDC (Top Dead Center) cylinder 1 — align timing marks.',
      'Check valve clearances on cylinder 1 with feeler gauges: intake 0.18–0.22mm, exhaust 0.23–0.27mm.',
      'Rotate engine 180° for each subsequent cylinder in firing order (1-3-4-2).',
      'If any clearance is out of spec, record the measurement — shim adjustment requires removing camshaft. Note clearances for shop if adjustment needed.',
      'Install new valve cover gasket. Reinstall valve cover. Torque bolts in crisscross pattern: 10 N·m.',
      'Reinstall engine cover. Start engine and verify smooth idle.',
    ],
    parts: [
      { partNumber: '12290-59B-A01', description: 'NGK Laser Iridium Spark Plug (set of 4)', qty: 4, unit: 'each' },
      { partNumber: '12341-59B-003', description: 'Valve Cover Gasket Set', qty: 1, unit: 'set' },
    ],
  },

  {
    id: 'wo-serpentine',
    title: 'Serpentine Belt Inspection & Replacement',
    priority: 'medium',
    status: 'open',
    createdKm: 150000,
    createdAt: new Date().toISOString(),
    notes: 'Inspect now (belt replaced at 130,000 km). Due for replacement at 200,000 km or sooner if inspection shows cracking, glazing, or fraying. The serpentine belt drives the alternator and A/C compressor. Belt failure leaves you stranded.',
    procedure: [
      'With engine OFF and cold, locate serpentine belt on front of engine — runs around alternator, A/C compressor, and idler pulleys.',
      'Inspect belt surface: look for cracks across ribs, glazing (shiny surface), missing chunks, fraying on edges, or squealing sound when running.',
      'Check belt tension — should have minimal slack. Automatic tensioner maintains tension on 1.5T.',
      'Inspect tensioner pulley and idler pulleys — spin by hand with belt off, should rotate smoothly with no roughness or noise.',
      'TO REPLACE: Use 14mm socket or breaker bar on tensioner pulley bolt to relieve tension. Route new belt around all pulleys per belt routing diagram (on sticker near engine or in owner manual).',
      'Release tensioner. Verify belt is seated in all pulley grooves.',
      'Start engine and verify belt runs smoothly and quietly.',
      'Inspect tensioner spring tension — if tensioner cannot maintain proper tension, replace tensioner.',
    ],
    parts: [
      { partNumber: 'N/A', description: 'Gates K060825 or OEM Serpentine Belt', qty: 1, unit: 'each' },
    ],
  },

  {
    id: 'wo-radiatorhose',
    title: 'Radiator Hose Inspection & Replacement',
    priority: 'low',
    status: 'open',
    createdKm: 150000,
    createdAt: new Date().toISOString(),
    notes: 'Due at 200,000 km (proactive). Northern Ontario winters accelerate rubber degradation — temperature cycling from -40°C to operating temp stresses hoses more than southern climates. Inspect now for cracking or swelling. A burst hose causes immediate overheating and potential engine damage.',
    procedure: [
      'Allow engine to cool completely.',
      'Inspect upper radiator hose: from radiator top to engine. Squeeze firmly — should feel firm and springy, not soft/mushy or hard/brittle.',
      'Inspect lower radiator hose: from radiator bottom to water pump. Same squeeze test.',
      'Inspect both hoses for surface cracks, swelling, oil contamination, or chafing from nearby components.',
      'Inspect hose clamps — should be tight with no corrosion. Replace spring clamps with screw clamps if corroded.',
      'Check overflow/reservoir hose from radiator to coolant reservoir.',
      'TO REPLACE UPPER HOSE: Drain coolant first (open petcock). Loosen clamps, twist and pull hose off. Install new hose, position clamps past bead, tighten clamps.',
      'TO REPLACE LOWER HOSE: Drain coolant completely. May need to raise vehicle for access. Follow same clamp procedure.',
      'Refill with Honda Type 2 50/50 mix. Bleed air from system by running engine with reservoir cap off until thermostat opens.',
      'Check for leaks at all clamp connections.',
    ],
    parts: [
      { partNumber: '19501-5AA-A01', description: 'Upper Radiator Hose', qty: 1, unit: 'each' },
      { partNumber: '19502-5AA-A01', description: 'Lower Radiator Hose', qty: 1, unit: 'each' },
    ],
  },

  {
    id: 'wo-chassis',
    title: 'Brakes & Chassis Inspection',
    priority: 'medium',
    status: 'open',
    createdKm: 150000,
    createdAt: new Date().toISOString(),
    notes: 'Due at 170,000 km (20,000 km interval). White River gravel roads, potholes, and salt are hard on suspension and brake components. This full inspection catches problems before they become failures or safety issues. Take photos of worn components for your records.',
    procedure: [
      'Lift vehicle on jack stands. Remove all 4 wheels.',
      'BRAKES — Front: measure pad thickness (min 3mm). Inspect rotor surface for scoring, heat cracks, or rust pitting. Check rotor thickness with micrometer if available.',
      'BRAKES — Rear: same inspection as front. Check parking brake cable condition.',
      'CALIPERS: inspect for fluid leaks at piston seals and bleed screws. Check slide pin boots.',
      'BRAKE LINES: inspect rubber flex hoses for cracking or swelling. Inspect steel hard lines for rust.',
      'BALL JOINTS: grab tire at 9 and 3 o\'clock, attempt to wiggle — any movement is a concern. Grab at 12 and 6 o\'clock and wiggle for wheel bearing check.',
      'TIE ROD ENDS: grab steering linkage and attempt to move — no play should be present.',
      'CV AXLE BOOTS: inspect inner and outer boots on both front axles for cracking or grease sling.',
      'SWAY BAR: check end links for play, check sway bar bushings for cracking.',
      'STRUTS/SHOCKS: inspect for oil leakage on strut body. Push down on each corner — should rebound once and stop.',
      'WHEEL BEARINGS: spin each wheel by hand. Should rotate smoothly and quietly. No roughness.',
      'EXHAUST: visually inspect exhaust system for rust holes, loose hangers, or contact with body.',
      'UNDERCARRIAGE: general inspection for rust on frame rails, subframe, and floor pan.',
      'Reinstall wheels. Torque lug nuts 108 N·m.',
      'Record all findings with measurements and photos.',
    ],
    parts: [
      { partNumber: 'N/A', description: 'Inspection only — parts as needed based on findings', qty: 1, unit: 'each' },
    ],
  },

  {
    id: 'wo-pcv',
    title: 'PCV Valve Replacement',
    priority: 'low',
    status: 'open',
    createdKm: 150000,
    createdAt: new Date().toISOString(),
    notes: 'Previously replaced at 140,000 km. Next due at 280,000 km. The PCV (Positive Crankcase Ventilation) valve prevents crankcase pressure buildup and routes blow-by gases back into the intake. A failed PCV valve causes oil consumption, rough idle, and accelerates oil dilution on the 1.5T. CRITICAL: This valve is known to be extremely fragile on the 1.5T — heat soak the engine bay before attempting removal to soften the plastic.',
    procedure: [
      'CRITICAL WARNING: The PCV valve on the 2018 CR-V 1.5T is extremely fragile. The plastic breaks easily if forced cold. Heat soak the engine (run to operating temp, then let sit 15 min) before attempting removal.',
      'Locate PCV valve on driver side of engine — black plastic valve connected to a hose, mounted in valve cover.',
      'Disconnect the small hose from PCV valve — squeeze clip and pull straight off.',
      'Gently twist PCV valve counterclockwise — use your fingers only, NO tools unless absolutely necessary.',
      'If valve will not turn: apply penetrating oil (PB Blaster) around the base and wait 10 minutes. Try again with gentle twisting motion. DO NOT force.',
      'Once loose, pull PCV valve straight up to remove.',
      'Inspect the hose connected to PCV valve — replace if cracked or hardened.',
      'Install new valve — hand press straight down, twist clockwise to lock. Should snap into place.',
      'Reconnect hose — push firmly until clip snaps.',
      'Start engine. Listen for hissing near valve cover — indicates improper seal.',
      'Check for oil leaks around PCV valve base.',
    ],
    parts: [
      { partNumber: '17130-5A2-A01', description: 'OEM PCV Valve — 2018 CR-V 1.5T (FRAGILE — handle carefully)', qty: 1, unit: 'each' },
    ],
  },

  {
    id: 'wo-battery',
    title: 'Battery Load Test & Replacement',
    priority: 'high',
    status: 'open',
    createdKm: 150000,
    createdAt: new Date().toISOString(),
    notes: 'Battery replaced at 130,000 km per your records — approximately 2–3 years ago depending on when it was replaced. Load test every fall before White River winter. A battery that passes a voltage test can still fail a load test. At -30°C to -40°C, a weak battery will not start the engine. Optima RedTop or OEM Honda replacement recommended.',
    procedure: [
      'Load test battery with a battery load tester (available at Canadian Tire or auto parts stores for ~$50, or free testing at most auto parts counters).',
      'Test should be done with battery at room temperature minimum — a cold battery will test weak even if healthy.',
      'Connect load tester per instructions. A healthy battery should hold above 9.6V under load for 15 seconds.',
      'Check battery date code — typically a sticker or stamp on top. Format varies by brand.',
      'Check battery terminals for corrosion (white/blue powdery buildup) — clean with baking soda solution and wire brush if present.',
      'Check battery hold-down clamp — must be secure. A loose battery vibrates and fails early.',
      'TO REPLACE: Disconnect negative (black) cable first, then positive (red).',
      'Remove hold-down clamp bolt.',
      'Lift out old battery — heavy, use proper lifting technique.',
      'Clean battery tray of any corrosion.',
      'Install new battery. Reconnect positive first, then negative.',
      'Reinstall hold-down clamp — battery must be secured.',
      'Apply terminal protector spray or petroleum jelly to terminals to prevent corrosion.',
      'Start vehicle and verify normal operation. Some systems (radio, power windows) may need to be reset.',
      'NOTE: After battery replacement, the idle may be rough for 10–15 minutes while the ECU relearns. This is normal.',
    ],
    parts: [
      { partNumber: 'N/A', description: 'Optima 35-RedTop or Honda OEM Battery', qty: 1, unit: 'each' },
      { partNumber: 'N/A', description: 'Terminal protector spray', qty: 1, unit: 'each' },
    ],
  },

  {
    id: 'wo-fuel',
    title: 'Fuel System Cleaner Treatment',
    priority: 'low',
    status: 'open',
    createdKm: 150000,
    createdAt: new Date().toISOString(),
    notes: 'Due at 165,000 km (10,000 km interval). GDI direct injectors accumulate deposits that reduce spray pattern quality, causing rough idle, misfires, and increased fuel consumption. Use BG 44K or Chevron Techron — add to fuel tank. Always use top-tier fuel (Petro-Canada, Shell V-Power) in White River — these contain higher concentrations of detergent additives.',
    procedure: [
      'Purchase BG 44K or Chevron Techron Complete Fuel System Cleaner.',
      'Add entire contents of one bottle to nearly empty fuel tank.',
      'Fill tank with premium top-tier fuel (Petro-Canada 91 or Shell V-Power).',
      'Drive normally — cleaner works through the fuel system over the next tank.',
      'For best results, drive a mix of highway and city over the next 500 km to work the cleaner through the full temperature range.',
      'NOTE: Do not use cheap no-name fuel additives — they can damage injector seals. BG 44K and Techron are the two proven options.',
      'Long-term: always use top-tier fuel at stations like Petro-Canada or Shell. Avoid no-name stations for regular use on this engine.',
    ],
    parts: [
      { partNumber: 'N/A', description: 'BG 44K or Chevron Techron Fuel System Cleaner', qty: 1, unit: 'bottle' },
    ],
  },

  {
    id: 'wo-undercoat',
    title: 'Undercoating — Annual Rust Protection',
    priority: 'medium',
    status: 'open',
    createdKm: 150000,
    createdAt: new Date().toISOString(),
    notes: 'Annual service — call Alisats Rust Proofing every May. White River road salt is one of the biggest threats to reaching 500,000 km. Frame rust, subframe corrosion, and brake line deterioration are all salt-related failures. Annual undercoating is one of the best investments for Northern Ontario vehicles.',
    procedure: [
      'Call Alisats Rust Proofing in May to schedule appointment.',
      'Before appointment: wash undercarriage thoroughly at coin wash to remove salt and dirt buildup from winter.',
      'Inform shop of any areas that need extra attention — wheel wells, subframe, brake line routing.',
      'After treatment: avoid washing undercarriage for at least 1 week to allow coating to fully cure.',
      'After the curing period, inspect treated areas to verify full coverage.',
      'Visually inspect brake lines, fuel lines, and frame rails while vehicle is on the hoist during undercoating appointment.',
      'Request spray inside door sills and rocker panels if shop offers this service.',
    ],
    parts: [
      { partNumber: 'N/A', description: 'Alisats Rust Proofing — $300 CAD', qty: 1, unit: 'service' },
    ],
  },

]
